version: 2
jobs:
   test:
     docker:
       - image: katalonstudio/katalon
     steps:
       - checkout
       - run: 
            name: Execute Katalon Tests
            command: cd KatalonStudio/Int;katalon-execute.sh -noSplash -consoleLog -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/IntPlan" 
       - store-test_results:
            path: ./KatalonStudio/report
       - store-artifacts:
            path: ./KatalonStudio/report

workflows:
  version: 2
  katalon-workflow:
    jobs:
      - test:
          filters: 
            branches:
               only: KatalonUITestInt
          context: TestContext
