version: 2
jobs:
   test:
     docker:
       - image: katalonstudio/katalon
     steps:
       - checkout
       - run: 
            name: Execute Katalon Tests
            command: cd 'Katalon Studio'/Int;katalon-execute.sh -noSplash -consoleLog -browserType="Chrome" -retry=0 -statusDelay=15 -projectPath='Int.prj'   -testSuitePath="Test Suites/IntPlan" -apiKey=${api-key} -executionProfile="default"
       - store-test_results:
            path: './Katalon Studio/report'
       - store-artifacts:
            path: './Katalon Studio/report'

workflows:
  version: 2
  katalon-workflow:
    jobs:
      - test:
          filters: 
            branches:
               only: KatalonUITestInt
          context: TestContext
